### ISSUE TITLE
支持ignore配置

### ISSUE THREAD

**Issue by shepherdwind** [node-modules/loading#15]
自动载入services包得时候，有时候services下需要util，这时候只能把util放到和services目录同级了。

但是util只是为services服务的，这时候最好还是util放在services目录下。

我觉得增加ignore配置，或者默认把util目录忽略不load了。

**Comment by fengmk2** [comment]
加吧，提交 pr

**Comment by hemanth** [comment]
Ok, I will make guess and won't using any tool to translate, the above line reads: `PR is welcomed`, correct?

**Comment by fengmk2** [comment]
@hemanth Haha, you can read Chinese now!

**Comment by hemanth** [comment]
@fengmk2 xiè xie :+1:
